version: 2
jobs:
  build:
    docker:
      - image: koocook/koocook-dj:dev
        auth:
          username: $KC_DK_USER
          password: $KC_DK_PSWD

    working_directory: ~/koocook-dj

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Migrating models to the database
          command: |
            python3 manage.py migrate

      - run:
          name: Ensuring installed dependencies
          command: |
            python3 -m venv --system-site-packages venv/
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}vv

      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python manage.py test

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
  deploy:
    docker:
      - image: koocook/koocook-dj:dev
        auth:
          username: $KC_DK_USER
          password: $KC_DK_PSWD

    working_directory: ~/koocook-dj

    steps:
      - checkout

      - run:
          name: Trigger the Build Job on the main repo
          command: |
            printf "Triggering an $MAIN_PROJECT build on the $CIRCLE_BRANCH branch\n\n"
            BUILD_INFO=$(curl -X POST -H -d \
                "{}" \
                "https://circleci.com/api/v1/project/$ORGANIZATION/$MAIN_PROJECT/tree/$CIRCLE_BRANCH?circle-token=$CIRCLE_TOKEN")
            printf "\n\nBuild triggered\n\n"
            printf "Follow the progress of the build on \nhttps://circleci.com/gh/$ORGANIZATION/$MAIN_PROJECT/tree/$CIRCLE_BRANCH"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
