version: 2
jobs:
  build:
    docker:
      - image: koocook/koocook-dj
        auth:
          username: $KC_DK_USER
          password: $KC_DK_PSWD

    working_directory: ~/koocook-dj

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}vv

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
