# Generated by Django 2.2.7 on 2019-12-01 11:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import koocook_core.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('koocook_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koocookuser',
            name='preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=koocook_core.models.user._default_preferences),
        ),
        migrations.AlterField(
            model_name='koocookuser',
            name='user_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=koocook_core.models.user._default_preferences),
        ),
        migrations.AlterUniqueTogether(
            name='recipevisit',
            unique_together={('user', 'recipe'), ('ip_address', 'user', 'recipe')},
        ),
    ]
