# Generated by Django 2.2.7 on 2019-11-26 13:53

from django.db import migrations, models
import django.db.models.deletion
import koocook_core.models.base
import koocook_core.models.review


class Migration(migrations.Migration):

    dependencies = [
        ('koocook_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='aggregate_rating',
            field=models.OneToOneField(blank=True, default=koocook_core.models.review.create_empty_aggregate_rating, null=True, on_delete=django.db.models.deletion.PROTECT, to='koocook_core.AggregateRating'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='koocook_core.Author')),
            ],
            bases=(koocook_core.models.base.SerialisableModel, models.Model),
        ),
    ]
