# Generated by Django 2.2.5 on 2019-11-17 15:47

from django.db import migrations, models
import django.db.models.deletion
import koocook_core.models.review


class Migration(migrations.Migration):

    dependencies = [
        ('koocook_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='aggregate_rating',
            field=models.OneToOneField(blank=True, default=koocook_core.models.review.create_empty_aggregate_rating, on_delete=django.db.models.deletion.PROTECT, to='koocook_core.AggregateRating'),
        ),
    ]
