# Generated by Django 3.0 on 2019-12-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koocook_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'label')},
        ),
    ]
