# Generated by Django 2.2.7 on 2019-11-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koocook_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('date_first_visited', models.DateTimeField(auto_now_add=True)),
                ('date_last_visited', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koocook_core.Recipe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='koocook_core.KoocookUser')),
            ],
            options={
                'verbose_name': 'Recipe visit count',
                'db_table': 'koocook_core_recipe_visit',
                'unique_together': {('ip_address', 'recipe'), ('user', 'recipe')},
            },
        ),
    ]
