# Generated by Django 2.2.7 on 2019-12-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koocook_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_equipment',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_equipment',
            field=models.ManyToManyField(blank=True, to='koocook_core.RecipeEquipment'),
        ),
    ]
