# Generated by Django 2.2.7 on 2019-11-30 17:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koocook_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koocookuser',
            name='preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='koocookuser',
            name='user_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
