# Generated by Django 2.2.5 on 2019-11-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koocook_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='nutrition_info',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_cuisine',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_instructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_yield',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
    ]
