# Generated by Django 2.2.7 on 2019-11-26 13:55

from django.db import migrations, models
import django.db.models.deletion
import koocook_core.models.review


class Migration(migrations.Migration):

    dependencies = [
        ('koocook_core', '0002_auto_20191126_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='aggregate_rating',
            field=models.OneToOneField(blank=True, default=koocook_core.models.review.create_empty_aggregate_rating, null=True, on_delete=django.db.models.deletion.PROTECT, to='koocook_core.AggregateRating'),
        ),
    ]
