# Generated by Django 2.2.7 on 2019-12-13 08:03

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koocook_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='koocookuser',
            options={'default_related_name': 'koocook_user'},
        ),
        migrations.AddField(
            model_name='koocookuser',
            name='avatar',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='koocookuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='koocook_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
